### ISSUE TITLE
[Translate-ID] Bantu saya untuk menerjemahkan javascript-question

### ISSUE THREAD

**Issue by burhanahmeed** [burhanahmeed/cara-kontribusi-open-source#1]
Bantu terjemahkan kedalam Bahasa Indonesia pada berkas `/id-ID/README.md`

Cheers!!!

**Comment by berhanxyz** [comment]
Saya ingin menerjemahkan yang nomor 1

**Comment by fiqriachmada** [comment]
Saya ingin menerjemahkan nomer 8

**Comment by joshuanatanielnm** [comment]
Saya ingin menerjemahkan nomer 22

**Comment by mulkiah** [comment]
Saya ingin menerjemahkan nomor 9

**Comment by babul28** [comment]
Saya ingin menerjemahkan yang nomor 28

**Comment by grikomsn** [comment]
Saya ingin menerjemahkan nomor `[object Object]`

**Comment by Iiqbal2000** [comment]
Saya ingin menerjemahkan nomor 7

**Comment by ilhambara** [comment]
Saya ingin menerjemahkan nomor 18

**Comment by mrizkyaly** [comment]
Saya ingin menerjemahkan nomor 20

**Comment by MuliaHartawan** [comment]
Saya ingin menerjemahkan nomor 12

**Comment by baralogi** [comment]
Saya ingin menerjemahkan nomor 91

**Comment by tiyan-attirmidzi** [comment]
Saya ingin menerjemahkan yang nomor 3

**Comment by fatik07** [comment]
saya ingin menerjemahkan nomor 21
